# Dev Tools Hooks Configuration
# Copy this file to .dev-hooks.yml in your project root

# Pre-commit commands
# These commands run before each commit
# If any command fails, the commit is aborted
pre-commit:
  # Enable/disable pre-commit checks (default: true)
  enabled: true

  # Commands to run before commit
  commands:
    # Example: Run linter
    - name: "Lint Check"
      run: "ruff check src/"

    # Example: Type checking
    - name: "Type Check"
      run: "mypy src/"

    # Example: Format check
    - name: "Format Check"
      run: "ruff format --check src/"

# Pre-push commands
# These commands run before pushing to remote
# If any command fails, the push is aborted
pre-push:
  # Enable/disable pre-push checks (default: true)
  enabled: true

  # Skip branch name validation (default: false)
  skip_branch_validation: false

  # Commands to run before push
  commands:
    # Example: Run tests
    - name: "Run Tests"
      run: "pytest"

# Docker support
# If your project runs in Docker, configure it here
docker:
  # Enable docker execution (default: false)
  enabled: false

  # Container name or service name (for docker-compose)
  container: "app"

  # Use docker-compose instead of docker exec (default: false)
  compose: true

  # docker-compose file path (default: docker-compose.yml)
  compose_file: "docker-compose.yml"

# ============================================================================
# Examples for different project types
# ============================================================================

# --- Python Project ---
# pre-commit:
#   commands:
#     - name: "Lint"
#       run: "ruff check ."
#     - name: "Types"
#       run: "mypy src/"
#     - name: "Format"
#       run: "ruff format --check ."
# pre-push:
#   commands:
#     - name: "Tests"
#       run: "pytest -v"

# --- Node.js Project ---
# pre-commit:
#   commands:
#     - name: "Lint"
#       run: "npm run lint"
#     - name: "Types"
#       run: "npm run typecheck"
# pre-push:
#   commands:
#     - name: "Tests"
#       run: "npm test"
#     - name: "Build"
#       run: "npm run build"

# --- PHP/Drupal Project (Dockerized) ---
# docker:
#   enabled: true
#   compose: true
#   container: "php"
# pre-commit:
#   commands:
#     - name: "PHPCS"
#       run: "vendor/bin/phpcs --standard=Drupal web/modules/custom"
# pre-push:
#   commands:
#     - name: "PHPUnit"
#       run: "vendor/bin/phpunit"

# --- Go Project ---
# pre-commit:
#   commands:
#     - name: "Vet"
#       run: "go vet ./..."
#     - name: "Fmt"
#       run: "test -z $(gofmt -l .)"
# pre-push:
#   commands:
#     - name: "Tests"
#       run: "go test ./..."
#     - name: "Build"
#       run: "go build ./..."
